Repository mash-up-kr/TwoToo_iOS, pull requests merged in 2023-06, with the labels that each got.

#1 네트워크 모듈 작업
  Core/Network/Package.swift
  Core/Network/README.md
  Core/Network/Sources/Network/Network.swift
  Core/Network/Sources/Network/NetworkConfiguration.swift
  Core/Network/Sources/Network/NetworkConnectionStatus.swift
  Core/Network/Sources/Network/NetworkManager.swift
  Core/Network/Tests/NetworkTests/NetworkManagerSpec.swift
  Core/Network/Tests/NetworkTests/NetworkTests.swift
  TwoToo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: enhancement

#3 모듈 의존관계 수정
  README.md
  Scene/NicknameRegistScene/Package.swift
  Scene/SceneKit/Package.swift
Labels: documentation

#4 Utils 관련 메서드 작업
  Core/Util/Sources/Util/DateFormatter.swift
  Core/Util/Sources/Util/Optional+.swift
  Core/Util/Sources/Util/SceneUtils/UICollectionReusableView+.swift
  Core/Util/Sources/Util/SceneUtils/UICollectionView.swift
  Core/Util/Sources/Util/SceneUtils/UIComponentBased.swift
  Core/Util/Sources/Util/SceneUtils/UIStackView+.swift
  Core/Util/Sources/Util/SceneUtils/UITableView+.swift
  Core/Util/Sources/Util/SceneUtils/UIView+.swift
  Core/Util/Sources/Util/SceneUtils/addAction+.swift
Labels: enhancement

#7 폰트 로드 되지 않는 오류 수정
  Core/DesignSystem/Package.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Font/Font.swift
  TwoToo/AppDelegate.swift
  TwoToo/Info.plist
  TwoToo/SceneDelegate.swift
Labels: 🐛 bug

#5 공통 토스트 작업
  Core/DesignSystem/Sources/DesignSystem/DesignSystem.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/Toast.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Extention/UIWindow+.swift
  TwoToo/SceneDelegate.swift
  TwoToo/ViewController.swift
Labels: ✨ Feature

#10 로그인 화면 시나리오 로직 작업
  Scene/LoginScene/README.md
  Scene/LoginScene/Sources/LoginScene/LoginInteractor.swift
  Scene/LoginScene/Sources/LoginScene/LoginModels.swift
  Scene/LoginScene/Sources/LoginScene/LoginPresenter.swift
  Scene/LoginScene/Sources/LoginScene/LoginSceneFactory.swift
  Scene/LoginScene/Sources/LoginScene/LoginWorker.swift
  Scene/LoginScene/Tests/LoginSceneTests/LoginInteractorSpec.swift
Labels: 📚 documentation, ✨ Feature, 🐨 경훈

#17 [Re] 디자인시스템 네비게이션 바 작업
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/NavigationBar/TTNavigationBar.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/NavigationBar/TTNavigationDetailBar.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo/NaviTestViewController.swift
  TwoToo/SceneDelegate.swift
Labels: ✨ Feature

#22 🐛 resultView 내에 화면 레이아웃을 못잡는 현상 수정
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTPopup.swift
  TwoToo/ViewController.swift
Labels: 🐛 bug

#20 ♻️ 팝업 뷰 레이아웃 정비 (딤 처리 추가)
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTPopup.swift
  TwoToo/ViewController.swift
Labels: ♻️ Refactor

#21 ♻️ 팝업 버튼 정비
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTPopup.swift
  TwoToo/ViewController.swift
Labels: ♻️ Refactor

#19 [Re] 디자인시스템 팝업 작업
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTPopup.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Extention/UILabel+.swift
  TwoToo/ViewController.swift
Labels: ✨ Feature

#18 [Re] 디자인시스템 버튼 작업
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/Buttons/TTPrimaryButton.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/Buttons/TTPrimaryButtonType.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/Buttons/TTTagButton.swift
Labels: ✨ Feature

#24 홈 화면 엔티티, 시나리오 명세 및 테스트 코드, 로직 작업
  Scene/HomeScene/README.md
  Scene/HomeScene/Sources/HomeScene/HomeInteractor.swift
  Scene/HomeScene/Sources/HomeScene/HomeModels.swift
  Scene/HomeScene/Sources/HomeScene/HomePresenter.swift
  Scene/HomeScene/Sources/HomeScene/HomeRouter.swift
  Scene/HomeScene/Sources/HomeScene/HomeSceneFactory.swift
  Scene/HomeScene/Sources/HomeScene/HomeWorker.swift
  Scene/HomeScene/Tests/HomeSceneTests/HomeInteractorSpec.swift
Labels: 📚 documentation, ✨ Feature, 🐯 지인

#26 홈 화면 매핑 시나리오 명세 및 테스트 코드, 로직 작업
  Scene/HomeScene/README.md
  Scene/HomeScene/Sources/HomeScene/HomeModels.swift
  Scene/HomeScene/Sources/HomeScene/HomePresenter.swift
  Scene/HomeScene/Tests/HomeSceneTests/Mapping/ChallengeBeforeStartMappingSpec.swift
  Scene/HomeScene/Tests/HomeSceneTests/Mapping/ChallengeCompletedMappingSpec.swift
  Scene/HomeScene/Tests/HomeSceneTests/Mapping/ChallengeInProgressMappingSpec.swift
  Scene/HomeScene/Tests/HomeSceneTests/Mapping/CompletedMappingSpec.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistModels.swift
Labels: 📚 documentation, ✨ Feature, 🐯 지인

#23 디자인시스템 텍스트필드 작업
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTTextField.swift
  Core/Util/Sources/Util/SceneUtils/UITextField+.swift
Labels: ✨ Feature

#27 화면별 바텀시트 작업
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/BottomSheet/Layout/SelfSizingScrollView.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/BottomSheet/PushView/TTBottomSheetPushViewController.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/BottomSheet/TTBottomSheetViewController.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TextView/TTTextView.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/BottomSheet/ChallengeCertificateBottomSheetPhotoView.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/BottomSheet/ChallengeCertificateBottomSheetViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/BottomSheet/ChallengeRecommendBottomSheetViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/BottomSheet/ChallengeRecommendTagView.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/BottomSheet/NudgeSendBottomSheetViewController.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/BottomSheet/PraiseSendBottomSheetViewController.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo/BottomSheetTestViewController.swift
  TwoToo/SceneDelegate.swift
Labels: ✨ Feature

#25 디자인시스템 바텀시트 / PlaceHolder 텍스트뷰 작업
  Core/DesignSystem/Package.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/BottomSheet/Layout/SelfSizingScrollView.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/BottomSheet/Layout/TouchBlockIntrinsicPanelLayout.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/BottomSheet/TTBottomSheetViewController.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TextView/TTTextView.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/BottomSheet/ChallengeCertificateBottomSheetPhotoView.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/BottomSheet/ChallengeCertificateBottomSheetViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/BottomSheet/ChallengeRecommendBottomSheetViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/BottomSheet/ChallengeRecommendTagView.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/BottomSheet/NudgeSendBottomSheetViewController.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/BottomSheet/PraiseSendBottomSheetViewController.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TwoToo/SceneDelegate.swift
Labels: ✨ Feature
