Repository mash-up-kr/TwoToo_iOS, pull requests merged in 2023-08, with the labels that each got.

#73 챌린지 필수입력, 선택입력 키보드에 따른 위치 변경
  Core/DesignSystem/Sources/DesignSystem/Resources/Colors.xcassets/Grey Color/Grey_700.colorset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Sources/Color/Pallete.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Color/UIColor+.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTTextField.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/Toast.swift
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/ChallengeRecommendPresenter.swift
Labels: 🐛 bug, 🐨 경훈, ✈️ ASAP

#76 사용성 개선 및 챌린지 히스토리 화면 구현
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_yellow.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_yellow.imageset/icon_home_yellow.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_yellow.imageset/icon_home_yellow@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_yellow.imageset/icon_home_yellow@3x.png
  Core/Local/Sources/Local/LocalDataSource.swift
  Core/Util/Sources/Util/Structures/Formatter.swift
  Core/Worker/Sources/Worker/LocalWorker/HomeLocalWorker.swift
  Core/Worker/Sources/Worker/LocalWorker/MeLocalWorker.swift
  Core/Worker/Sources/Worker/NetworkWorker/ChallengeDetailNetworkWorker.swift
  Core/Worker/Sources/Worker/NetworkWorker/ChallengeQuitNetworkWorker.swift
  Core/Worker/Sources/Worker/NetworkWorker/HomeNetworkWorker.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateViewController.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateWorker.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputInteractor.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailViewController.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/Cell/CertificateTableViewCell.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryInteractor.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryPresenter.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryRouter.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistorySceneFactory.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryViewController.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryWorker.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryInteractor.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryViewController.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryWorker.swift
  Scene/HomeScene/Sources/HomeScene/HomeInteractor.swift
  Scene/HomeScene/Sources/HomeScene/HomeModels.swift
  Scene/HomeScene/Sources/HomeScene/HomePresenter.swift
  Scene/HomeScene/Sources/HomeScene/HomeRouter.swift
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
  Scene/HomeScene/Sources/HomeScene/HomeWorker.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeInProgressView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Common/TTProgressBar.swift
  Scene/HomeScene/Sources/HomeScene/Views/Common/TopChallengeInfoView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/Component/InduceCertificationView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/MyFlowerView.swift
  Scene/MainScene/Sources/MainScene/MainRouter.swift
  Scene/MainScene/Sources/MainScene/MainTabBarController.swift
  Scene/MainScene/Sources/MainScene/Views/MainTabBar.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistViewController.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendViewController.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendViewController.swift
  Scene/SplashScene/Sources/SplashScene/SplashWorker.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo/AppDelegate.swift
Labels: 🐛 bug, ✨ Feature, 🐻‍❄️ 건우, ✈️ ASAP

#77 히스토리 화면 네트워크 연동
  Core/Worker/Sources/Worker/LocalWorker/HomeLocalWorker.swift
  Core/Worker/Sources/Worker/NetworkWorker/HistoryNetworkWorker.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/Cell/CertificateTableViewCell.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryPresenter.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryInteractor.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryModels.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryPresenter.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryRouter.swift
  Scene/HistoryScene/Sources/HistoryScene/HistorySceneFactory.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryViewController.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryWorker.swift
  Scene/HomeScene/Sources/HomeScene/HomeWorker.swift
Labels: ✨ Feature, 🐻‍❄️ 건우, ✈️ ASAP

#78 챌린지 수락 기능 구현 및 생성, 수락 분기 처리 추가
  Core/Worker/Sources/Worker/NetworkWorker/ChallengeApproveNetworkWorker.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateInteractor.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/Views/ChallengeCertificatePhotoView.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmInteractor.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmRouter.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmSceneFactory.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmViewController.swift
  Scene/ChallengeCreateFinishScene/Sources/ChallengeCreateFinishScene/ChallengeCreateFinishViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputRouter.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputViewController.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectRouter.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectSceneFactory.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectWorker.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryViewController.swift
  Scene/HomeScene/Sources/HomeScene/HomeInteractor.swift
  Scene/HomeScene/Sources/HomeScene/HomeRouter.swift
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendInteractor.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendInteractor.swift
Labels: 🐛 bug, ✨ Feature, 🐻‍❄️ 건우, ✈️ ASAP

#79 IndicatorView 작업
  Core/DesignSystem/Package.swift
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/indicator/flower lottie.dataset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/indicator/flower lottie.dataset/flower lottie_1.json
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/Loading.swift
Labels: ✨ Feature, 🐨 경훈

#80 앱 아이콘 작업
  TwoToo.xcodeproj/project.pbxproj
  TwoToo/Assets.xcassets/AppIcon.appiconset/Contents.json
  TwoToo/Assets.xcassets/AppIcon.appiconset/iOS_appicon.png
Labels: ✨ Feature, 🐨 경훈

#81 종이재질 배경 Util 작업
  Core/Util/Package.swift
  Core/Util/Sources/Util/Extensions/UIView+.swift
  Core/Util/Sources/Util/Resources/Assets.xcassets/Contents.json
  Core/Util/Sources/Util/Resources/Assets.xcassets/background/Contents.json
  Core/Util/Sources/Util/Resources/Assets.xcassets/background/home_background.imageset/Contents.json
  Core/Util/Sources/Util/Resources/Assets.xcassets/background/home_background.imageset/home_background 1.png
  Core/Util/Sources/Util/Resources/Assets.xcassets/background/home_background.imageset/home_background@2x 1.png
  Core/Util/Sources/Util/Resources/Assets.xcassets/background/home_background.imageset/home_background@3x 1.png
Labels: ✨ Feature, 🐨 경훈, ✈️ ASAP

#82 타임존 이슈 및 기타 버그 수정
  Core/Worker/Sources/Worker/NetworkWorker/ChallengeFinishNetworkWorker.swift
  Core/Worker/Sources/Worker/NetworkWorker/HistoryNetworkWorker.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryPresenter.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
  Scene/HistoryScene/Sources/HistoryScene/HistorySceneFactory.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryViewController.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryWorker.swift
  Scene/HomeScene/Sources/HomeScene/HomeWorker.swift
  Scene/MainScene/Sources/MainScene/MainInteractor.swift
  Scene/MainScene/Sources/MainScene/MainRouter.swift
  Scene/MainScene/Sources/MainScene/MainSceneFactory.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoInteractor.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoPresenter.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoSceneFactory.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoWorker.swift
  TwoToo/SceneDelegate.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ✈️ ASAP

#83 종이 재질 배경 적용 작업
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/BottomSheet/TTBottomSheetViewController.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmViewController.swift
  Scene/ChallengeCreateFinishScene/Sources/ChallengeCreateFinishScene/ChallengeCreateFinishViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/ChallengeRecommendViewController.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryViewController.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectViewController.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryViewController.swift
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
  Scene/InvitationSendScene/Sources/InvitationSendScene/InvitationSendViewController.swift
  Scene/InvitationWaitScene/Sources/InvitationWaitScene/InvitationWaitViewController.swift
  Scene/LoginScene/Sources/LoginScene/LoginViewController.swift
  Scene/MyInfoScene/Sources/MyInfoScene/Cell/MyInfoTableViewCell.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistViewController.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendViewController.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendViewController.swift
  Scene/SplashScene/Sources/SplashScene/SplashViewController.swift
Labels: ✨ Feature, 🐨 경훈, ✈️ ASAP

#84 화면 별 로딩 처리 및 물뿌리기 로티 추가
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/indicator/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/Loading.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateViewController.swift
  Scene/ChallengeCreateFinishScene/Sources/ChallengeCreateFinishScene/ChallengeCreateFinishViewController.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryViewController.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectViewController.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryViewController.swift
  Scene/HomeScene/Sources/HomeScene/Assets/Assets.xcassets/watering_lottie.dataset/Contents.json
  Scene/HomeScene/Sources/HomeScene/Assets/Assets.xcassets/watering_lottie.dataset/watering_lottie.json
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/Component/InduceCertificationView.swift
  Scene/InvitationSendScene/Sources/InvitationSendScene/InvitationSendViewController.swift
  Scene/InvitationWaitScene/Sources/InvitationWaitScene/InvitationWaitViewController.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistViewController.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendViewController.swift
Labels: ✨ Feature, 🐯 지인, ✈️ ASAP

#86 스플래시 이미지 변경
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_splash_icon.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_splash_icon.imageset/app_splash_icon.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_splash_icon.imageset/app_splash_icon@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_splash_icon.imageset/app_splash_icon@3x.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/NavigationBar/TTNavigationDetailBar.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputInteractor.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryViewController.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryViewController.swift
  Scene/SplashScene/Sources/SplashScene/SplashViewController.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ✈️ ASAP

#87 디자인 1차 QA 작업
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailPresenter.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailViewController.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryViewController.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeCompletedView.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeInProgressView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/Component/InduceCertificationView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/MyFlowerView.swift
Labels: ✈️ ASAP, ⚡️ QA

#88 긴 챌린지 이름 짤리는 버그 해결
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryViewController.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeCompletedView.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeInProgressView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Common/TopChallengeInfoView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/Component/InduceCertificationView.swift
Labels: ✈️ ASAP, ⚡️ QA

#89 챌린지 삭제 오류 수정
  Core/Worker/Sources/Worker/NetworkWorker/ChallengeQuitNetworkWorker.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ✈️ ASAP, ⚡️ QA

#90 회원 탈퇴 기능 구현
  Core/Worker/Sources/Worker/LocalWorker/CommonAppleLoginWorker.swift
  Core/Worker/Sources/Worker/LocalWorker/MeLocalWorker.swift
  Core/Worker/Sources/Worker/LocalWorker/MyInfoLocalWorker.swift
  Scene/LoginScene/Sources/LoginScene/LoginWorker.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoInteractor.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoModels.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoPresenter.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoSceneFactory.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoWorker.swift
Labels: ✨ Feature, 🐨 경훈, ✈️ ASAP

#92 인증 물뿌리개 터치가 안되는 현상 수정
  Scene/HomeScene/Sources/HomeScene/Views/Flower/MyFlowerView.swift
Labels: 🐛 bug, ✈️ ASAP, 🔥 hot fix

#95 히스토리 이미지 딤 처리
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/Cell/CertificateTableViewCell.swift
  Scene/InvitationWaitScene/Sources/InvitationWaitScene/InvitationWaitViewController.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
Labels: ✈️ ASAP, ⚡️ QA

#96 홈 화면 꽃 진행도 상태 수정
  Scene/HomeScene/Sources/HomeScene/HomeWorker.swift
Labels: ✈️ ASAP, ⚡️ QA

#93 바텀시트 높이 및 레이아웃 재조정
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/BottomSheet/Layout/SelfSizingScrollView.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/BottomSheet/TTBottomSheetViewController.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateViewController.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendViewController.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendViewController.swift
Labels: ✈️ ASAP, ⚡️ QA

#94 키보드 활성화 시 컴포넌트 레이아웃 수정
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputViewController.swift
Labels: ✈️ ASAP, ⚡️ QA
