Repository mash-up-kr/TwoToo_iOS, pull requests merged in 2023-12, with the labels that each got.

#127 마이페이지 만든이들 URL 변경
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoInteractor.swift
Labels: 🐨 경훈, ♻️ Refactor, ✈️ ASAP

#125 강제 업데이트 기능 구현
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/update/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/update/update_icon.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/update/update_icon.imageset/update_icon@1x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/update/update_icon.imageset/update_icon@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/update/update_icon.imageset/update_icon@3x.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Core/Worker/Sources/Worker/NetworkWorker/AppVersionNetworkWorker.swift
  Scene/SplashScene/Sources/SplashScene/SplashInteractor.swift
  Scene/SplashScene/Sources/SplashScene/SplashModels.swift
  Scene/SplashScene/Sources/SplashScene/SplashPresenter.swift
  Scene/SplashScene/Sources/SplashScene/SplashSceneFactory.swift
  Scene/SplashScene/Sources/SplashScene/SplashViewController.swift
  Scene/SplashScene/Sources/SplashScene/SplashWorker.swift
Labels: ✨ Feature, 🐨 경훈, ✈️ ASAP

#126 초대 대기 화면 나가기 기능 구현
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_exit.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_exit.imageset/icon_bubble_tail_exit.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_exit.imageset/icon_bubble_tail_exit@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_exit.imageset/icon_bubble_tail_exit@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Colors.xcassets/Primary Color/Primary.colorset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/NavigationBar/TTNavigationBar.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/SpeechBubbleView.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Font/UIFont+.swift
  Core/Local/Sources/Local/LocalDataSource.swift
  Scene/InvitationWaitScene/Sources/InvitationWaitScene/InvitationWaitInteractor.swift
  Scene/InvitationWaitScene/Sources/InvitationWaitScene/InvitationWaitSceneFactory.swift
  Scene/InvitationWaitScene/Sources/InvitationWaitScene/InvitationWaitViewController.swift
  Scene/InvitationWaitScene/Sources/InvitationWaitScene/InvitationWaitWorker.swift
  TwoToo/SceneDelegate.swift
Labels: ✨ Feature, 🐯 지인, ✈️ ASAP
