Repository mash-up-kr/TwoToo_iOS, pull requests merged in 2023-10, with the labels that each got.

#99 챌린지 수락 전 챌린지 삭제하기 기능 구현
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/NavigationBar/TTNavigationDetailBar.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTPopup.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmInteractor.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmModels.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmPresenter.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmSceneFactory.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmViewController.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmWorker.swift
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputViewController.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryModels.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryPresenter.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryViewController.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectViewController.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo/NaviTestViewController.swift
Labels: ✨ Feature, 🐯 지인, ⚡️ QA

#103 히스토리 화면 이슈 수정
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_small/img_buds.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_small/img_buds.imageset/img_buds.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_small/img_buds.imageset/img_buds@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_small/img_buds.imageset/img_buds@3x.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Core/Network/Sources/Network/NetworkConfiguration.swift
  Core/Worker/Sources/Worker/NetworkWorker/HistoryNetworkWorker.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryPresenter.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ⚡️ QA

#98 회원탈퇴 (네트워킹) 기능 구현
  Core/Worker/Sources/Worker/NetworkWorker/SignOutNetworkWorker.swift
  Scene/LoginScene/Sources/LoginScene/LoginWorker.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoInteractor.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoModels.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoPresenter.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoSceneFactory.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoWorker.swift
Labels: ✨ Feature, 🐻‍❄️ 건우, ⚡️ QA

#100 챌린지 기본 정보 입력 화면 이슈 수정
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputInteractor.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputViewController.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ⚡️ QA

#101 챌린지 추가 정보 입력 화면 이슈 수정
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputViewController.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ⚡️ QA

#102 꽃 선택 화면 이슈 수정
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectViewController.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ⚡️ QA

#104 내 정보 화면 이슈 수정
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoInteractor.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ⚡️ QA

#107 상단 챌린지 정보 뷰 화살표 추가
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_title_arrow.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_title_arrow.imageset/icon_title_arrow.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_title_arrow.imageset/icon_title_arrow@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_title_arrow.imageset/icon_title_arrow@3x.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Scene/HomeScene/Sources/HomeScene/Views/Common/TopChallengeInfoView.swift
Labels: ✨ Feature, 🐯 지인, ✈️ ASAP, ⚡️ QA

#108 찌르기 화면 이슈 수정
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendViewController.swift
Labels: 🐛 bug, 🐨 경훈, ⚡️ QA

#106 히스토리 완료된 챌린지 삭제하기 구현
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTPopup.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmPresenter.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryPresenter.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryViewController.swift
Labels: ✨ Feature, 🐯 지인, ⚡️ QA

#109 사진 관련 버그 수정 및 개선
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateInteractor.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateWorker.swift
  Scene/ChallengeHistoryDetailScene/Package.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailInteractor.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailModels.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailPresenter.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailViewController.swift
Labels: 🐛 bug, ✨ Feature, 🐻‍❄️ 건우, ⚡️ QA

#110 히스토리 관련 버그 수정 및 기능 구현
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_state_icon/icon_challenge_progress.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_state_icon/icon_challenge_progress.imageset/icon_challenge_progress-2.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_state_icon/icon_challenge_progress.imageset/icon_challenge_progress-3.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_state_icon/icon_challenge_progress.imageset/icon_challenge_progress2.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Core/Worker/Sources/Worker/NetworkWorker/HistoryNetworkWorker.swift
  Scene/HistoryScene/Sources/HistoryScene/Cell/HistoryCollectionViewCell.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryModels.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryPresenter.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryWorker.swift
Labels: 🐛 bug, 🐨 경훈, ✈️ ASAP, ⚡️ QA

#111 닉네임 변경 기능 구현
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/myinfo/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/myinfo/icon_edit.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/myinfo/icon_edit.imageset/icon_edit.pdf
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Core/Worker/Sources/Worker/NetworkWorker/ChangeNicknameNetworkWorker.swift
  Scene/MyInfoScene/Package.swift
  Scene/MyInfoScene/Sources/ChangeNicknameScene/ChangeNicknameInteractor.swift
  Scene/MyInfoScene/Sources/ChangeNicknameScene/ChangeNicknameModels.swift
  Scene/MyInfoScene/Sources/ChangeNicknameScene/ChangeNicknamePresenter.swift
  Scene/MyInfoScene/Sources/ChangeNicknameScene/ChangeNicknameRouter.swift
  Scene/MyInfoScene/Sources/ChangeNicknameScene/ChangeNicknameSceneFactory.swift
  Scene/MyInfoScene/Sources/ChangeNicknameScene/ChangeNicknameViewController.swift
  Scene/MyInfoScene/Sources/ChangeNicknameScene/ChangeNicknameWorker.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoInteractor.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoModels.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoPresenter.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoRouter.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoWorker.swift
Labels: ✨ Feature, 🐨 경훈, ✈️ ASAP

#117 메인 화면 랜딩 시에 검은 화면 약 0.1 초간 노출 이슈 해결
  Scene/MainScene/Sources/MainScene/MainTabBarController.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ⚡️ QA

#116 로그아웃 시 로컬 스토리지 값 제거
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoSceneFactory.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoWorker.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ⚡️ QA

#115 홈 화면 리로드 시점 추가 (didBecomeActive)
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ⚡️ QA

#114 Firebase Analytics, Crashlytics 환경 세팅
  Scene/LoginScene/Package.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo.xcodeproj/xcshareddata/xcschemes/TwoToo.xcscheme
  TwoToo/AppDelegate.swift
  TwoToo/GoogleService-Info.plist
  TwoToo/Info.plist
Labels: ✨ Feature, 🐻‍❄️ 건우, ⚡️ QA

#113 히스토리 리스트 딤처리
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/Cell/CertificateTableViewCell.swift
  TwoToo.xcodeproj/project.pbxproj
Labels: ✨ Feature, 🐻‍❄️ 건우, ⚡️ QA

#112 꽃말 카드 팝업 기능 추가
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/flowerPopup_background.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/flowerPopup_background.imageset/flowerPopup_background.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/flowerPopup_background.imageset/flowerPopup_background@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/flowerPopup_background.imageset/flowerPopup_background@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/bubble_challenge_fail.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/bubble_challenge_fail.imageset/bubble_challenge_fail.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/bubble_challenge_fail.imageset/bubble_challenge_fail@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/bubble_challenge_fail.imageset/bubble_challenge_fail@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_flowerLanguage.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_flowerLanguage.imageset/icon_bubble_flowerLanguage.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_flowerLanguage.imageset/icon_bubble_flowerLanguage@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_flowerLanguage.imageset/icon_bubble_flowerLanguage@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_not_mate.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_not_mate.imageset/icon_bubble_not_mate 1.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_not_mate.imageset/icon_bubble_not_mate@2x 1.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_not_mate.imageset/icon_bubble_not_mate@3x 1.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_my.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_my.imageset/img_yellow_tail.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_my.imageset/img_yellow_tail@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_my.imageset/img_yellow_tail@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_partner.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_partner.imageset/img_pink_tail.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_partner.imageset/img_pink_tail@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_tail_partner.imageset/img_pink_tail@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_write.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_write.imageset/icon_bubble_write 1.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_write.imageset/icon_bubble_write@2x 1.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/speechBubble/icon_bubble_write.imageset/icon_bubble_write@3x 1.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Scene/HomeScene/Sources/HomeScene/HomeModels.swift
  Scene/HomeScene/Sources/HomeScene/HomePresenter.swift
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeCompletedView.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeInProgressView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Common/TTFlowerPopup.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/MyFlowerTopView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/MyFlowerView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/PartnerFlowerTopView.swift
Labels: ✨ Feature, 🐯 지인

#118 히스토리 관련 이슈 수정
  Scene/HistoryScene/Sources/HistoryScene/HistoryViewController.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryWorker.swift
Labels: 🐛 bug, 🐨 경훈, ⚡️ QA

#121 회원 탈퇴, 챌린지 삭제하기 Popup 문구 수정
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTPopup.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryPresenter.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoModels.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
Labels: 🐨 경훈, ⚡️ QA

#119 마이페이지, 닉네임 변경 페이지 Font 및 alignment 수정
  Scene/MyInfoScene/Sources/ChangeNicknameScene/ChangeNicknameViewController.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
Labels: 🐨 경훈, ⚡️ QA

#120 홈 프로그레스 바 큰 사이즈 화면 대응
  Scene/HomeScene/Sources/HomeScene/Views/Common/TTProgressBar.swift
Labels: 🐛 bug, ✈️ ASAP, ⚡️ QA

#122 RC3 추가적인 이슈 수정
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_state_icon/icon_challenge_progress.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_state_icon/icon_challenge_progress.imageset/icon_challenge_progress-3.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_state_icon/icon_challenge_progress.imageset/icon_challenge_progress.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_state_icon/icon_challenge_progress.imageset/icon_challenge_progress@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_state_icon/icon_challenge_progress.imageset/icon_challenge_progress@3x.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTPopup.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmViewController.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryModels.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryPresenter.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryWorker.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryViewController.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeCompletedView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/MyFlowerTopView.swift
  Scene/InvitationSendScene/Sources/InvitationSendScene/InvitationSendViewController.swift
  Scene/InvitationWaitScene/Sources/InvitationWaitScene/InvitationWaitViewController.swift
Labels: 🐛 bug, 🐻‍❄️ 건우, ✈️ ASAP, ⚡️ QA
