Repository mash-up-kr/TwoToo_iOS, pull requests merged in 2023-07, with the labels that each got.

#29 공통 컴포넌트 TagView 작업
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TagView/TTTagView.swift
  TwoToo/ViewController.swift
Labels: ✨ Feature, ✈️ ASAP

#32 메인 탭바 작업
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_brown.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_brown.imageset/icon_home_brown.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_brown.imageset/icon_home_brown@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_brown.imageset/icon_home_brown@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_pink.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_pink.imageset/icon_home_pink.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_pink.imageset/icon_home_pink@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_home_pink.imageset/icon_home_pink@3x.png
  Core/Util/Sources/Util/UIDevice+.swift
  Core/Util/Sources/Util/UIWindow+.swift
  Scene/HistoryScene/Sources/HistoryScene/HistorySceneFactory.swift
  Scene/MainScene/Sources/MainScene/MainInteractor.swift
  Scene/MainScene/Sources/MainScene/MainModels.swift
  Scene/MainScene/Sources/MainScene/MainPresenter.swift
  Scene/MainScene/Sources/MainScene/MainRouter.swift
  Scene/MainScene/Sources/MainScene/MainSceneFactory.swift
  Scene/MainScene/Sources/MainScene/MainTabBarController.swift
  Scene/MainScene/Sources/MainScene/MainViewController.swift
  Scene/MainScene/Sources/MainScene/Views/MainTabBar.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoSceneFactory.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TwoToo/SceneDelegate.swift
Labels: ✨ Feature, ✈️ ASAP

#34 유틸 키보드 감지 관련 메소드 작업
  Core/Util/Sources/Util/Constants/DateFormatType.swift
  Core/Util/Sources/Util/DateFormatter.swift
  Core/Util/Sources/Util/Extensions/Date+.swift
  Core/Util/Sources/Util/Extensions/Notification+.swift
  Core/Util/Sources/Util/Extensions/Optional+.swift
  Core/Util/Sources/Util/Extensions/String+.swift
  Core/Util/Sources/Util/Extensions/UICollectionReusableView+.swift
  Core/Util/Sources/Util/Extensions/UICollectionView.swift
  Core/Util/Sources/Util/Extensions/UIControl+.swift
  Core/Util/Sources/Util/Extensions/UIStackView+.swift
  Core/Util/Sources/Util/Extensions/UITableView+.swift
  Core/Util/Sources/Util/Extensions/UITextField+.swift
  Core/Util/Sources/Util/Extensions/UIView+.swift
  Core/Util/Sources/Util/Protocols/UIComponentBased.swift
  Core/Util/Sources/Util/SceneUtils/UIView+.swift
  Core/Util/Sources/Util/SceneUtils/addAction+.swift
  Core/Util/Sources/Util/Structures/ClosureSleeve.swift
  Core/Util/Sources/Util/Structures/Formatter.swift
  Core/Util/Sources/Util/Traits/KeyboardDelegate.swift
  Core/Util/Sources/Util/Traits/Scene.swift
Labels: ✈️ ASAP

#38 칭찬하기 화면 시나리오 명세 및 테스트 코드, 로직 작업
  Scene/PraiseSendScene/README.md
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendInteractor.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendModels.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendPresenter.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendRouter.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendSceneFactory.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendWorker.swift
  Scene/PraiseSendScene/Tests/PraiseSendSceneTests/PraiseSendInteractorSpec.swift
Labels: 📚 documentation, ✨ Feature, 🐻‍❄️ 건우

#39 로그인 화면 UI 구현
  .gitignore
  Scene/LoginScene/Package.swift
  Scene/LoginScene/Sources/LoginScene/Assets/Assets.xcassets/kakaoLogin.imageset/Contents.json
  Scene/LoginScene/Sources/LoginScene/Assets/Assets.xcassets/kakaoLogin.imageset/button-2.png
  Scene/LoginScene/Sources/LoginScene/Assets/Assets.xcassets/kakaoLogin.imageset/button-3.png
  Scene/LoginScene/Sources/LoginScene/Assets/Assets.xcassets/kakaoLogin.imageset/button.png
  Scene/LoginScene/Sources/LoginScene/Cell/LoginCollectionViewCell.swift
  Scene/LoginScene/Sources/LoginScene/LoginModels.swift
  Scene/LoginScene/Sources/LoginScene/LoginPresenter.swift
  Scene/LoginScene/Sources/LoginScene/LoginViewController.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo/AppDelegate.swift
  TwoToo/Info.plist
  TwoToo/SceneDelegate.swift
  TwoToo/TwoToo.entitlements
Labels: ✨ Feature, 🐨 경훈, 🎨 Scene

#37 인증 화면 UI 구현
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/Buttons/TTPrimaryButtonType.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TextView/TTTextView.swift
  Scene/ChallengeCertificateScene/Package.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/BottomSheet/ChallengeCertificateBottomSheetViewController.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateModels.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificatePresenter.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateRouter.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateSceneFactory.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateViewController.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateWorker.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/Views/ChallengeCertificatePhotoView.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo/Info.plist
  TwoToo/SceneDelegate.swift
Labels: ✨ Feature, 🐻‍❄️ 건우, 🎨 Scene

#40 칭찬하기 화면 UI 구현
  Scene/PraiseSendScene/Sources/PraiseSendScene/BottomSheet/PraiseSendBottomSheetViewController.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendModels.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendPresenter.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendRouter.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendSceneFactory.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendViewController.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo/AppDelegate.swift
  TwoToo/SceneDelegate.swift
Labels: ✨ Feature, 🐻‍❄️ 건우, ✈️ ASAP, 🎨 Scene

#41 찌르기 화면 UI 및 로직 구현
  Scene/NudgeSendScene/README.md
  Scene/NudgeSendScene/Sources/NudgeSendScene/BottomSheet/NudgeSendBottomSheetViewController.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendInteractor.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendModels.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendPresenter.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendRouter.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendSceneFactory.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendViewController.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendWorker.swift
  Scene/NudgeSendScene/Tests/NudgeSendSceneTests/NudgeSendInteractorSpec.swift
  TwoToo/SceneDelegate.swift
Labels: 📚 documentation, ✨ Feature, 🐻‍❄️ 건우, ✈️ ASAP, 🎨 Scene

#42 요청 보내기 화면 UI 구현
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/Buttons/TTPrimaryButtonType.swift
  Scene/InvitationSendScene/Sources/InvitationSendScene/InvitationSendViewController.swift
  TwoToo/SceneDelegate.swift
Labels: 🐻‍❄️ 건우, ✈️ ASAP, 🎨 Scene

#36 닉네임 설정 UI 구현 및 로직 작업
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTTextField.swift
  Core/Local/Sources/Local/LocalDataSource.swift
  Core/Worker/Sources/Worker/InvitedUserLocalWorker.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/Commponent/IntroTagView.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistInteractor.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistModels.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistPresenter.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistSceneFactory.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistViewController.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistWorker.swift
  TwoToo/SceneDelegate.swift
Labels: ✨ Feature, 🐯 지인, 🎨 Scene

#43 대기 화면 UI 구현
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/Buttons/TTPrimaryButtonType.swift
  Scene/InvitationWaitScene/Sources/InvitationWaitScene/InvitationWaitPresenter.swift
  Scene/InvitationWaitScene/Sources/InvitationWaitScene/InvitationWaitViewController.swift
  TwoToo/SceneDelegate.swift
Labels: 🐻‍❄️ 건우, ✈️ ASAP, 🎨 Scene

#44 챌린지 추천 화면 UI 및 로직 구현
  Scene/ChallengeCreateScene/README.md
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/BottomSheet/ChallengeRecommendBottomSheetViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/ChallengeRecommendInteractor.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/ChallengeRecommendModels.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/ChallengeRecommendPresenter.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/ChallengeRecommendRouter.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/ChallengeRecommendSceneFactory.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/ChallengeRecommendViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/Views/ChallengeRecommendTagView.swift
  TwoToo/SceneDelegate.swift
Labels: 📚 documentation, ✨ Feature, 🐻‍❄️ 건우, ✈️ ASAP, 🎨 Scene

#46 Flower 공통 Worker 구현
  Core/Worker/Sources/Worker/FlowerMappingWorker.swift
Labels: ✨ Feature, 🐨 경훈

#49 FlowerMapping Small 꽃 추가 작업
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_small/flower_small_sunflower.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_small/flower_small_sunflower.imageset/Property 1=flower_sunflower_sm.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_small/flower_small_sunflower.imageset/Property 1=flower_sunflower_sm@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/flower_small/flower_small_sunflower.imageset/Property 1=flower_sunflower_sm@3x.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Core/Worker/Sources/Worker/FlowerMappingWorker.swift
Labels: ✈️ ASAP

#50 디자인시스템 TTTextView maxCount 추가
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TextView/TTTextView.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateViewController.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendViewController.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendViewController.swift
Labels: ✨ Feature, 🐨 경훈, ✈️ ASAP

#53 스플래시 및 온보딩 라우팅 작업
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_icon.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_icon.imageset/app_icon.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_icon.imageset/app_icon@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_icon.imageset/app_icon@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_logo.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_logo.imageset/app_logo.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_logo.imageset/app_logo@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/app_icon/app_logo.imageset/app_logo@3x.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Scene/InvitationSendScene/Sources/InvitationSendScene/InvitationSendInteractor.swift
  Scene/InvitationSendScene/Sources/InvitationSendScene/InvitationSendSceneFactory.swift
  Scene/InvitationSendScene/Tests/InvitationSendSceneTests/InvitationSendInteractorSpec.swift
  Scene/LoginScene/Sources/LoginScene/Cell/LoginCollectionViewCell.swift
  Scene/LoginScene/Sources/LoginScene/LoginInteractor.swift
  Scene/LoginScene/Sources/LoginScene/LoginSceneFactory.swift
  Scene/LoginScene/Sources/LoginScene/LoginViewController.swift
  Scene/LoginScene/Tests/LoginSceneTests/LoginInteractorSpec.swift
  Scene/SplashScene/Sources/SplashScene/SplashInteractor.swift
  Scene/SplashScene/Sources/SplashScene/SplashSceneFactory.swift
  Scene/SplashScene/Sources/SplashScene/SplashViewController.swift
  Scene/SplashScene/Sources/SplashScene/SplashWorker.swift
  Scene/SplashScene/Tests/SplashSceneTests/SplashInteractorSpec.swift
  TwoToo/SceneDelegate.swift
Labels: 🐻‍❄️ 건우, ✈️ ASAP

#47 챌린지 필수 입력 화면 UI 및 로직 구현
  Core/Util/Sources/Util/Extensions/String+.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputInteractor.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputModels.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputPresenter.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputRouter.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputSceneFactory.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputViewController.swift
Labels: ✨ Feature, 🐨 경훈, 🎨 Scene

#52 챌린지 히스토리 화면 시나리오 명세 및 테스트 코드, 로직 작업
  Scene/ChallengeHistoryScene/README.md
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryInteractor.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryModels.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryPresenter.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryRouter.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistorySceneFactory.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryWorker.swift
  Scene/ChallengeHistoryScene/Tests/ChallengeHistorySceneTests/ChallengeHistoryInteractorSpec.swift
Labels: 📚 documentation, ✨ Feature, 🐯 지인, ✈️ ASAP

#51 챌린지 추가 정보 입력 UI 및 로직 구현
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputInteractor.swift
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputRouter.swift
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputSceneFactory.swift
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputViewController.swift
Labels: ✨ Feature, 🐨 경훈, 🎨 Scene

#48 홈화면 UI 연동
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/Buttons/TTPrimaryButtonType.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTPopup.swift
  Core/Worker/Sources/Worker/FlowerMappingWorker.swift
  Scene/HomeScene/.swiftpm/xcode/xcshareddata/xcschemes/HomeSceneTests.xcscheme
  Scene/HomeScene/README.md
  Scene/HomeScene/Sources/HomeScene/HomeInteractor.swift
  Scene/HomeScene/Sources/HomeScene/HomeModels.swift
  Scene/HomeScene/Sources/HomeScene/HomePresenter.swift
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
  Scene/HomeScene/Sources/HomeScene/HomeWorker.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeCompletedView.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeInProgressView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Common/TTProgressBar.swift
  Scene/HomeScene/Sources/HomeScene/Views/Common/TrailingInfoStackView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/MyFlowerView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/PartnerFlowerView.swift
  Scene/HomeScene/Tests/HomeSceneTests/Mapping/ChallengeInProgressMappingSpec.swift
  Scene/HomeScene/Tests/HomeSceneTests/Mapping/CompletedMappingSpec.swift
  TwoToo/SceneDelegate.swift
Labels: ✨ Feature, 🐻‍❄️ 건우, ✈️ ASAP, 🎨 Scene

#54 히스토리 화면 UI 및 로직 구현
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/history_card.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/history_card.imageset/card_history.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/history_card.imageset/card_history@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/history_card.imageset/card_history@3x.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Core/Util/Sources/Util/Constants/DateFormatType.swift
  Core/Util/Sources/Util/Extensions/String+.swift
  Scene/HistoryScene/Sources/HistoryScene/Cell/HistoryCollectionViewCell.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryInteractor.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryModels.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryPresenter.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryRouter.swift
  Scene/HistoryScene/Sources/HistoryScene/HistorySceneFactory.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryViewController.swift
  Scene/MainScene/Sources/MainScene/MainRouter.swift
Labels: 📚 documentation, ✨ Feature, 🐯 지인, 🎨 Scene

#58 챌린지 생성 완료 UI 및 로직 구현
  Scene/ChallengeCreateFinishScene/Sources/ChallengeCreateFinishScene/ChallengeCreateFinishInteractor.swift
  Scene/ChallengeCreateFinishScene/Sources/ChallengeCreateFinishScene/ChallengeCreateFinishRouter.swift
  Scene/ChallengeCreateFinishScene/Sources/ChallengeCreateFinishScene/ChallengeCreateFinishSceneFactory.swift
  Scene/ChallengeCreateFinishScene/Sources/ChallengeCreateFinishScene/ChallengeCreateFinishViewController.swift
Labels: ✨ Feature, 🐨 경훈, 🎨 Scene

#56 카카오 로그인 구현
  Core/Network/Sources/Network/NetworkConfiguration.swift
  Core/Network/Sources/Network/NetworkManager.swift
  Core/Util/Sources/Util/Structures/TransitionOptions.swift
  Core/Worker/Sources/Worker/LocalWorker/InvitationLocalWorker.swift
  Core/Worker/Sources/Worker/LocalWorker/InvitedUserLocalWorker.swift
  Core/Worker/Sources/Worker/LocalWorker/MeLocalWorker.swift
  Core/Worker/Sources/Worker/LocalWorker/OnboardingLocalWorker.swift
  Core/Worker/Sources/Worker/MappingWorker/FlowerMappingWorker.swift
  Core/Worker/Sources/Worker/NetworkWorker/AuthNetworkWorker.swift
  Scene/LoginScene/Sources/LoginScene/LoginPresenter.swift
  Scene/LoginScene/Sources/LoginScene/LoginSceneFactory.swift
  Scene/LoginScene/Sources/LoginScene/LoginViewController.swift
  Scene/LoginScene/Sources/LoginScene/LoginWorker.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistSceneFactory.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistWorker.swift
  Scene/SplashScene/Sources/SplashScene/SplashWorker.swift
  TwoToo/AppDelegate.swift
  TwoToo/Info.plist
  TwoToo/SceneDelegate.swift
Labels: ✨ Feature, 🐻‍❄️ 건우

#55 챌린지 확인 화면 UI 및 비즈니스 로직 구현
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmInteractor.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmModels.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmPresenter.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmRouter.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmSceneFactory.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmViewController.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmWorker.swift
Labels: ✨ Feature, 🐨 경훈, 🎨 Scene

#60 닉네임 통신 연동
  Core/Worker/Sources/Worker/LocalWorker/InvitationLocalWorker.swift
  Core/Worker/Sources/Worker/LocalWorker/InvitedUserLocalWorker.swift
  Core/Worker/Sources/Worker/LocalWorker/MeLocalWorker.swift
  Core/Worker/Sources/Worker/LocalWorker/OnboardingLocalWorker.swift
  Core/Worker/Sources/Worker/NetworkWorker/NicknameNetworkWorker.swift
  Scene/LoginScene/Sources/LoginScene/LoginWorker.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistInteractor.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistModels.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistPresenter.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistSceneFactory.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistWorker.swift
  Scene/NicknameRegistScene/Tests/NicknameRegistSceneTests/NicknameRegistInteractorSpec.swift
Labels: ✨ Feature, 🐻‍❄️ 건우, ✈️ ASAP

#57 꽃 선택하기 화면 UI 및 로직 구현
  Core/DesignSystem/Sources/DesignSystem/Sources/Color/CGColor+.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Color/Pallete.swift
  Core/Worker/Package.swift
  Core/Worker/Sources/Worker/MappingWorker/FlowerMappingWorker.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/Cell/FlowerSelectCell.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectModels.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectPresenter.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectRouter.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectSceneFactory.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectViewController.swift
Labels: ✨ Feature, 🐨 경훈, 🎨 Scene

#59 챌린지 히스토리 UI 및 화면 로직 작업
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_certificate.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_certificate.imageset/history_certificate.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_certificate.imageset/history_certificate@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_certificate.imageset/history_certificate@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_fail.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_fail.imageset/history_fail.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_fail.imageset/history_fail@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_fail.imageset/history_fail@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_line.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_line.imageset/history_line.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_line.imageset/history_line@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_line.imageset/history_line@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_waiting.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_waiting.imageset/history_waiting.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_waiting.imageset/history_waiting@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/history/history_waiting.imageset/history_waiting@3x.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTPopup.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TagView/TTTagView.swift
  Core/Util/Sources/Util/Constants/DateFormatType.swift
  Core/Util/Sources/Util/Extensions/Date+.swift
  Core/Util/Sources/Util/Extensions/String+.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputInteractor.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/Cell/CertificateTableViewCell.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryModels.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryPresenter.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryRouter.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryViewController.swift
  Scene/HistoryScene/Sources/HistoryScene/HistoryPresenter.swift
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
  TwoToo/ViewController.swift
Labels: ✨ Feature, 🐯 지인, 🎨 Scene

#64 초대 통신 연동
  Core/Worker/Package.swift
  Scene/InvitationSendScene/Package.swift
  Scene/InvitationSendScene/Sources/InvitationSendScene/InvitationSendSceneFactory.swift
  Scene/InvitationSendScene/Sources/InvitationSendScene/InvitationSendWorker.swift
  Scene/NicknameRegistScene/Sources/NicknameRegistScene/NicknameRegistWorker.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo.xcodeproj/xcshareddata/xcschemes/TwoToo.xcscheme
  TwoToo/AppDelegate.swift
  TwoToo/Info.plist
  TwoToo/SceneDelegate.swift
  TwoToo/TwoToo.entitlements
Labels: ✨ Feature, 🐻‍❄️ 건우, ✈️ ASAP

#61 마이페이지 UI 및 로직 구현
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTSeparator.swift
  Scene/MainScene/Sources/MainScene/MainRouter.swift
  Scene/MyInfoScene/Sources/MyInfoScene/Cell/MyInfoTableViewCell.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoInteractor.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoModels.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoPresenter.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoRouter.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoSceneFactory.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoWorker.swift
Labels: ✨ Feature, 🐨 경훈, 🎨 Scene

#62 챌린지 필수입력에서 챌린지추천, 챌린지 선택입력 화면 전환 작업
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTTextField.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputInteractor.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputModels.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputPresenter.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputRouter.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputSceneFactory.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputViewController.swift
Labels: ✨ Feature, 🐨 경훈

#66 챌린지 확인에서 꽃 선택하기 화면 전환 작업
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmInteractor.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmRouter.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputInteractor.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputSceneFactory.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectSceneFactory.swift
Labels: ✨ Feature, 🐨 경훈

#69 필수입력 화면 컴파일 에러 해결
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputInteractor.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputSceneFactory.swift
Labels: 🐛 bug, 🐨 경훈, ✈️ ASAP

#67 챌린지 히스토리 상세 UI 및 화면 로직 작업
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/NavigationBar/TTNavigationBar.swift
  Core/Util/Sources/Util/Constants/DateFormatType.swift
  Core/Util/Sources/Util/Extensions/String+.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailInteractor.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailModels.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailPresenter.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailRouter.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailSceneFactory.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailViewController.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryInteractor.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryRouter.swift
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
Labels: ✨ Feature, 🐯 지인, 🎨 Scene

#70 바텀시트 화면 일괄 네트워크 연동
  Core/Network/Sources/Network/NetworkManager.swift
  Core/Worker/Sources/Worker/NetworkWorker/ChallengeFinishNetworkWorker.swift
  Core/Worker/Sources/Worker/NetworkWorker/CommentNetworkWorker.swift
  Core/Worker/Sources/Worker/NetworkWorker/CommitNetworkWorker.swift
  Core/Worker/Sources/Worker/NetworkWorker/StickNetworkWorker.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateInteractor.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateSceneFactory.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateWorker.swift
  Scene/HomeScene/Sources/HomeScene/HomeRouter.swift
  Scene/HomeScene/Sources/HomeScene/HomeSceneFactory.swift
  Scene/HomeScene/Sources/HomeScene/HomeWorker.swift
  Scene/LoginScene/Sources/LoginScene/LoginWorker.swift
  Scene/MainScene/Sources/MainScene/MainRouter.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendSceneFactory.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendWorker.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendInteractor.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendSceneFactory.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendWorker.swift
  TwoToo.xcodeproj/project.pbxproj
  TwoToo/AppDelegate.swift
  TwoToo/Info.plist
  TwoToo/TwoToo.entitlements
Labels: ✨ Feature, 🐻‍❄️ 건우, ✈️ ASAP

#71 홈 상태별 뷰 액션 로직 작업
  Scene/HomeScene/Sources/HomeScene/HomeInteractor.swift
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeAfterStartDateView.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeBeforeStartDateView.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeBeforeStartView.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeCompletedView.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeCreatedView.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeInProgressView.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeWaitingView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Flower/MyFlowerView.swift
Labels: ✨ Feature, 🐯 지인

#72 챌린지 생성 네트워크 연동
  Core/Util/Sources/Util/Constants/DateFormatType.swift
  Core/Util/Sources/Util/Extensions/String+.swift
  Core/Util/Sources/Util/Structures/Formatter.swift
  Core/Worker/Sources/Worker/NetworkWorker/ChallengeCreateNetworkWorker.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmRouter.swift
  Scene/ChallengeConfirmScene/Sources/ChallengeConfirmScene/ChallengeConfirmViewController.swift
  Scene/ChallengeCreateFinishScene/Sources/ChallengeCreateFinishScene/ChallengeCreateFinishRouter.swift
  Scene/ChallengeCreateFinishScene/Sources/ChallengeCreateFinishScene/ChallengeCreateFinishViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputRouter.swift
  Scene/ChallengeCreateScene/Sources/ChallengeAdditionalInfoInputScene/ChallengeAdditionalInfoInputViewController.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputRouter.swift
  Scene/ChallengeCreateScene/Sources/ChallengeEssentialInfoInputScene/ChallengeEssentialInfoInputViewController.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectInteractor.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectRouter.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectSceneFactory.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectViewController.swift
  Scene/FlowerSelectScene/Sources/FlowerSelectScene/FlowerSelectWorker.swift
  Scene/MainScene/Sources/MainScene/MainTabBarController.swift
Labels: ✨ Feature, 🐨 경훈, ✈️ ASAP

#74 마이 페이지 네트워크 연동 및 웹뷰 연동
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoInteractor.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoRouter.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoSceneFactory.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoViewController.swift
  Scene/MyInfoScene/Sources/MyInfoScene/MyInfoWorker.swift
Labels: ✨ Feature, 🐨 경훈

#75 애플로그인 구현
  Scene/LoginScene/Sources/LoginScene/AppleManager.swift
  Scene/LoginScene/Sources/LoginScene/LoginViewController.swift
  Scene/LoginScene/Sources/LoginScene/LoginWorker.swift
  TwoToo/Info.plist
Labels: ✨ Feature, 🐨 경훈
