Repository mash-up-kr/TwoToo_iOS, pull requests merged in 2024-01, with the labels that each got.

#128 강제 업데이트 오류 해결
  Core/Worker/Sources/Worker/NetworkWorker/AppVersionNetworkWorker.swift
  Scene/SplashScene/Sources/SplashScene/SplashInteractor.swift
Labels: 🐛 bug, 🐨 경훈, ✈️ ASAP

#129 챌린지 히스토리 퍼센테이지바 구현
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/TTProgressBar.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryModels.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryPresenter.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryViewController.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryWorker.swift
  Scene/HomeScene/Sources/HomeScene/HomeModels.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeCompletedView.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeInProgressView.swift
Labels: ✨ Feature, 🐯 지인

#130 칭찬하기 기능 Flow 수정
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailInteractor.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailModels.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailPresenter.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailRouter.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailSceneFactory.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailViewController.swift
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailWorker.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryInteractor.swift
  Scene/ChallengeHistoryScene/Sources/ChallengeHistoryScene/ChallengeHistoryRouter.swift
  Scene/HomeScene/Sources/HomeScene/HomeInteractor.swift
  Scene/HomeScene/Sources/HomeScene/HomeModels.swift
  Scene/HomeScene/Sources/HomeScene/HomePresenter.swift
  Scene/HomeScene/Sources/HomeScene/HomeRouter.swift
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
  Scene/HomeScene/Sources/HomeScene/HomeWorker.swift
Labels: ✨ Feature, 🐨 경훈

#131 SE에서 닉네임 변경 입력 시 키보드에 의해 화면 짤리는 문제 해결
  Scene/MyInfoScene/Sources/ChangeNicknameScene/ChangeNicknameViewController.swift
Labels: 🐛 bug, 🐨 경훈, ✈️ ASAP

#133 챌린지 완료 꽃말보기 공유 기능 추가
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_send_card.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_send_card.imageset/icon_send_card.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_send_card.imageset/icon_send_card@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/icon_send_card.imageset/icon_send_card@3x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/img_send_card_tooltip.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/img_send_card_tooltip.imageset/img_send_card_tooltip.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/img_send_card_tooltip.imageset/img_send_card_tooltip@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/main_icon/img_send_card_tooltip.imageset/img_send_card_tooltip@3x.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/SpeechBubbleView.swift
  Core/Util/Sources/Util/Constants/DateFormatType.swift
  Core/Util/Sources/Util/Extensions/String+.swift
  Scene/HomeScene/Sources/HomeScene/HomeInteractor.swift
  Scene/HomeScene/Sources/HomeScene/HomeModels.swift
  Scene/HomeScene/Sources/HomeScene/HomePresenter.swift
  Scene/HomeScene/Sources/HomeScene/HomeRouter.swift
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
  Scene/HomeScene/Sources/HomeScene/HomeWorker.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeInProgressView.swift
  Scene/HomeScene/Sources/HomeScene/Views/Common/TTCertificationSharePopup.swift
  Scene/HomeScene/Sources/HomeScene/Views/Common/TTFlowerPopup.swift
  Scene/HomeScene/Sources/HomeScene/Views/Common/TTLanguageFlowerSharePopup.swift
  Scene/HomeScene/Tests/HomeSceneTests/HomeInteractorSpec.swift
  Scene/HomeScene/Tests/HomeSceneTests/Mapping/ChallengeInProgressMappingSpec.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendPresenter.swift
Labels: ✨ Feature, 🐨 경훈

#134 SE 기기에서 바텀시트 올라갈 때 버튼 가리는 이슈 해결
  Core/DesignSystem/Sources/DesignSystem/Sources/Component/BottomSheet/Layout/SelfSizingScrollView.swift
  Scene/ChallengeCertificateScene/Sources/ChallengeCertificateScene/ChallengeCertificateViewController.swift
  Scene/HomeScene/Sources/HomeScene/Views/ChallengeCompletedView.swift
  Scene/NudgeSendScene/Sources/NudgeSendScene/NudgeSendViewController.swift
Labels: 🐛 bug, 🐯 지인, ✈️ ASAP

#132 홈 화면 챌린지 성공 공유 기능 추가
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/popup_ground.imageset/Contents.json
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/popup_ground.imageset/popup_ground.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/popup_ground.imageset/popup_ground@2x.png
  Core/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/background/popup_ground.imageset/popup_ground@3x.png
  Core/DesignSystem/Sources/DesignSystem/Sources/Assets/Assets.swift
  Scene/HomeScene/Sources/HomeScene/Assets/Assets.xcassets/celebrate_lottie.dataset/Contents.json
  Scene/HomeScene/Sources/HomeScene/Assets/Assets.xcassets/celebrate_lottie.dataset/lottie_celebrate.json
  Scene/HomeScene/Sources/HomeScene/HomeInteractor.swift
  Scene/HomeScene/Sources/HomeScene/HomeModels.swift
  Scene/HomeScene/Sources/HomeScene/HomePresenter.swift
  Scene/HomeScene/Sources/HomeScene/HomeViewController.swift
  Scene/HomeScene/Sources/HomeScene/Views/Common/TTChallengeCompleteSharePopup.swift
  Scene/HomeScene/Tests/HomeSceneTests/HomeInteractorSpec.swift
  Scene/HomeScene/Tests/HomeSceneTests/Mapping/ChallengeCompletedMappingSpec.swift
  Scene/HomeScene/Tests/HomeSceneTests/Mapping/ChallengeInProgressMappingSpec.swift
  Scene/HomeScene/Tests/HomeSceneTests/Mapping/CompletedMappingSpec.swift
Labels: ✨ Feature, 🐻‍❄️ 건우

#135 바텀시트 높이가 고정되지 않는 이슈 해결
  Scene/ChallengeCreateScene/Sources/ChallengeRecommendScene/ChallengeRecommendViewController.swift
  Scene/PraiseSendScene/Sources/PraiseSendScene/PraiseSendViewController.swift
Labels: 🐛 bug, 🐯 지인, ✈️ ASAP

#136 칭찬하기 플로우 로직 수정
  Scene/ChallengeHistoryDetailScene/Sources/ChallengeHistoryDetailScene/ChallengeHistoryDetailWorker.swift
Labels: 🐛 bug, 🐨 경훈, ✈️ ASAP
